//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Coach
    {
        public int Coach_ID { get; set; }
        public string Coach_Type { get; set; }
        public Nullable<int> Train_ID { get; set; }
        public Nullable<int> Number_Of_Seats { get; set; }
        public Nullable<double> Price { get; set; }
        public string Status { get; set; }
    
        public virtual Train Train { get; set; }
    }
}
