//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Train
    {
        public Train()
        {
            this.Coaches = new HashSet<Coach>();
            this.Tickets = new HashSet<Ticket>();
            this.Timetables = new HashSet<Timetable>();
        }
    
        public int Train_ID { get; set; }
        public string Train_Name { get; set; }
        public int Origin_Station_ID { get; set; }
        public int Destination_Station_ID { get; set; }
        public string Status { get; set; }
        public string Train_Type { get; set; }
    
        public virtual ICollection<Coach> Coaches { get; set; }
        public virtual Station Station { get; set; }
        public virtual Station Station1 { get; set; }
        public virtual ICollection<Ticket> Tickets { get; set; }
        public virtual ICollection<Timetable> Timetables { get; set; }
    }
}
