//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFBankTransfer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person_Accounts
    {
        public int Account_ID { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> Expiration_Date { get; set; }
        public string Card_Code { get; set; }
        public string CVV_CSC { get; set; }
        public Nullable<double> Total_Amount { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
    }
}
