//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Online_Railway_reservation_systemEntities : DbContext
    {
        public Online_Railway_reservation_systemEntities()
            : base("name=Online_Railway_reservation_systemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Coach> Coaches { get; set; }
        public virtual DbSet<Passenger> Passengers { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<Station> Stations { get; set; }
        public virtual DbSet<Ticket> Tickets { get; set; }
        public virtual DbSet<Timetable> Timetables { get; set; }
        public virtual DbSet<Train> Trains { get; set; }
        public virtual DbSet<User> Users { get; set; }
    
        public virtual int Add_Coaches(string coach_Type, Nullable<int> train_ID, Nullable<int> number_Of_Seats, Nullable<double> price, string status)
        {
            var coach_TypeParameter = coach_Type != null ?
                new ObjectParameter("Coach_Type", coach_Type) :
                new ObjectParameter("Coach_Type", typeof(string));
    
            var train_IDParameter = train_ID.HasValue ?
                new ObjectParameter("Train_ID", train_ID) :
                new ObjectParameter("Train_ID", typeof(int));
    
            var number_Of_SeatsParameter = number_Of_Seats.HasValue ?
                new ObjectParameter("Number_Of_Seats", number_Of_Seats) :
                new ObjectParameter("Number_Of_Seats", typeof(int));
    
            var priceParameter = price.HasValue ?
                new ObjectParameter("Price", price) :
                new ObjectParameter("Price", typeof(double));
    
            var statusParameter = status != null ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Add_Coaches", coach_TypeParameter, train_IDParameter, number_Of_SeatsParameter, priceParameter, statusParameter);
        }
    
        public virtual int Add_Passengers(string pNR, string passenger_Name, Nullable<System.DateTime> date_Of_Birth, string card_Code, string gender, string email, string phone_Number, string address)
        {
            var pNRParameter = pNR != null ?
                new ObjectParameter("PNR", pNR) :
                new ObjectParameter("PNR", typeof(string));
    
            var passenger_NameParameter = passenger_Name != null ?
                new ObjectParameter("Passenger_Name", passenger_Name) :
                new ObjectParameter("Passenger_Name", typeof(string));
    
            var date_Of_BirthParameter = date_Of_Birth.HasValue ?
                new ObjectParameter("Date_Of_Birth", date_Of_Birth) :
                new ObjectParameter("Date_Of_Birth", typeof(System.DateTime));
    
            var card_CodeParameter = card_Code != null ?
                new ObjectParameter("Card_Code", card_Code) :
                new ObjectParameter("Card_Code", typeof(string));
    
            var genderParameter = gender != null ?
                new ObjectParameter("Gender", gender) :
                new ObjectParameter("Gender", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var phone_NumberParameter = phone_Number != null ?
                new ObjectParameter("Phone_Number", phone_Number) :
                new ObjectParameter("Phone_Number", typeof(string));
    
            var addressParameter = address != null ?
                new ObjectParameter("Address", address) :
                new ObjectParameter("Address", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Add_Passengers", pNRParameter, passenger_NameParameter, date_Of_BirthParameter, card_CodeParameter, genderParameter, emailParameter, phone_NumberParameter, addressParameter);
        }
    
        public virtual int Add_Roles(string role_Name)
        {
            var role_NameParameter = role_Name != null ?
                new ObjectParameter("Role_Name", role_Name) :
                new ObjectParameter("Role_Name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Add_Roles", role_NameParameter);
        }
    
        public virtual int Add_Stations(string station_Name, Nullable<double> latitude, Nullable<double> longtitude, string status)
        {
            var station_NameParameter = station_Name != null ?
                new ObjectParameter("Station_Name", station_Name) :
                new ObjectParameter("Station_Name", typeof(string));
    
            var latitudeParameter = latitude.HasValue ?
                new ObjectParameter("Latitude", latitude) :
                new ObjectParameter("Latitude", typeof(double));
    
            var longtitudeParameter = longtitude.HasValue ?
                new ObjectParameter("Longtitude", longtitude) :
                new ObjectParameter("Longtitude", typeof(double));
    
            var statusParameter = status != null ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Add_Stations", station_NameParameter, latitudeParameter, longtitudeParameter, statusParameter);
        }
    
        public virtual int Add_Timetables(Nullable<System.DateTime> departure_Date, Nullable<System.TimeSpan> departure_Time, Nullable<System.DateTime> arrival_Date, Nullable<System.TimeSpan> arrival_Time, Nullable<double> distance, Nullable<int> train_ID)
        {
            var departure_DateParameter = departure_Date.HasValue ?
                new ObjectParameter("Departure_Date", departure_Date) :
                new ObjectParameter("Departure_Date", typeof(System.DateTime));
    
            var departure_TimeParameter = departure_Time.HasValue ?
                new ObjectParameter("Departure_Time", departure_Time) :
                new ObjectParameter("Departure_Time", typeof(System.TimeSpan));
    
            var arrival_DateParameter = arrival_Date.HasValue ?
                new ObjectParameter("Arrival_Date", arrival_Date) :
                new ObjectParameter("Arrival_Date", typeof(System.DateTime));
    
            var arrival_TimeParameter = arrival_Time.HasValue ?
                new ObjectParameter("Arrival_Time", arrival_Time) :
                new ObjectParameter("Arrival_Time", typeof(System.TimeSpan));
    
            var distanceParameter = distance.HasValue ?
                new ObjectParameter("Distance", distance) :
                new ObjectParameter("Distance", typeof(double));
    
            var train_IDParameter = train_ID.HasValue ?
                new ObjectParameter("Train_ID", train_ID) :
                new ObjectParameter("Train_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Add_Timetables", departure_DateParameter, departure_TimeParameter, arrival_DateParameter, arrival_TimeParameter, distanceParameter, train_IDParameter);
        }
    
        public virtual int Add_Trains(string train_Name, Nullable<int> origin_Station_ID, Nullable<int> destination_Station_ID, string status, string train_Type)
        {
            var train_NameParameter = train_Name != null ?
                new ObjectParameter("Train_Name", train_Name) :
                new ObjectParameter("Train_Name", typeof(string));
    
            var origin_Station_IDParameter = origin_Station_ID.HasValue ?
                new ObjectParameter("Origin_Station_ID", origin_Station_ID) :
                new ObjectParameter("Origin_Station_ID", typeof(int));
    
            var destination_Station_IDParameter = destination_Station_ID.HasValue ?
                new ObjectParameter("Destination_Station_ID", destination_Station_ID) :
                new ObjectParameter("Destination_Station_ID", typeof(int));
    
            var statusParameter = status != null ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(string));
    
            var train_TypeParameter = train_Type != null ?
                new ObjectParameter("Train_Type", train_Type) :
                new ObjectParameter("Train_Type", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Add_Trains", train_NameParameter, origin_Station_IDParameter, destination_Station_IDParameter, statusParameter, train_TypeParameter);
        }
    
        public virtual int Add_Users(string username, string password, string email, string phone_Number, string gender, string security_Code, Nullable<int> role_ID)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var phone_NumberParameter = phone_Number != null ?
                new ObjectParameter("Phone_Number", phone_Number) :
                new ObjectParameter("Phone_Number", typeof(string));
    
            var genderParameter = gender != null ?
                new ObjectParameter("Gender", gender) :
                new ObjectParameter("Gender", typeof(string));
    
            var security_CodeParameter = security_Code != null ?
                new ObjectParameter("Security_Code", security_Code) :
                new ObjectParameter("Security_Code", typeof(string));
    
            var role_IDParameter = role_ID.HasValue ?
                new ObjectParameter("Role_ID", role_ID) :
                new ObjectParameter("Role_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Add_Users", usernameParameter, passwordParameter, emailParameter, phone_NumberParameter, genderParameter, security_CodeParameter, role_IDParameter);
        }
    
        public virtual int Cancel_Ticket(Nullable<int> ticket_ID, string status)
        {
            var ticket_IDParameter = ticket_ID.HasValue ?
                new ObjectParameter("Ticket_ID", ticket_ID) :
                new ObjectParameter("Ticket_ID", typeof(int));
    
            var statusParameter = status != null ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Cancel_Ticket", ticket_IDParameter, statusParameter);
        }
    
        public virtual int Delete_Coaches(Nullable<int> coach_ID)
        {
            var coach_IDParameter = coach_ID.HasValue ?
                new ObjectParameter("Coach_ID", coach_ID) :
                new ObjectParameter("Coach_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Delete_Coaches", coach_IDParameter);
        }
    
        public virtual int Delete_Passengers(string pNR)
        {
            var pNRParameter = pNR != null ?
                new ObjectParameter("PNR", pNR) :
                new ObjectParameter("PNR", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Delete_Passengers", pNRParameter);
        }
    
        public virtual int Delete_Roles(Nullable<int> role_ID)
        {
            var role_IDParameter = role_ID.HasValue ?
                new ObjectParameter("Role_ID", role_ID) :
                new ObjectParameter("Role_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Delete_Roles", role_IDParameter);
        }
    
        public virtual int Delete_Stations(Nullable<int> station_ID)
        {
            var station_IDParameter = station_ID.HasValue ?
                new ObjectParameter("Station_ID", station_ID) :
                new ObjectParameter("Station_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Delete_Stations", station_IDParameter);
        }
    
        public virtual int Delete_Tickets(Nullable<int> ticket_ID)
        {
            var ticket_IDParameter = ticket_ID.HasValue ?
                new ObjectParameter("Ticket_ID", ticket_ID) :
                new ObjectParameter("Ticket_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Delete_Tickets", ticket_IDParameter);
        }
    
        public virtual int Delete_Timetables(Nullable<int> timetable_ID)
        {
            var timetable_IDParameter = timetable_ID.HasValue ?
                new ObjectParameter("Timetable_ID", timetable_ID) :
                new ObjectParameter("Timetable_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Delete_Timetables", timetable_IDParameter);
        }
    
        public virtual int Delete_Trains(Nullable<int> train_ID)
        {
            var train_IDParameter = train_ID.HasValue ?
                new ObjectParameter("Train_ID", train_ID) :
                new ObjectParameter("Train_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Delete_Trains", train_IDParameter);
        }
    
        public virtual int Delete_Users(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Delete_Users", usernameParameter);
        }
    
        public virtual ObjectResult<Get_All_Coaches_Result> Get_All_Coaches()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_All_Coaches_Result>("Get_All_Coaches");
        }
    
        public virtual ObjectResult<Get_All_Ticket_v2_Result> Get_All_Ticket_v2()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_All_Ticket_v2_Result>("Get_All_Ticket_v2");
        }
    
        public virtual ObjectResult<get_All_Timetables_v2_Result> get_All_Timetables_v2()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_All_Timetables_v2_Result>("get_All_Timetables_v2");
        }
    
        public virtual ObjectResult<Get_All_Train_v2_Result> Get_All_Train_v2()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_All_Train_v2_Result>("Get_All_Train_v2");
        }
    
        public virtual ObjectResult<Get_All_User_v2_Result> Get_All_User_v2()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_All_User_v2_Result>("Get_All_User_v2");
        }
    
        public virtual ObjectResult<get_Coach_By_ID_Result> get_Coach_By_ID(Nullable<int> coach_ID)
        {
            var coach_IDParameter = coach_ID.HasValue ?
                new ObjectParameter("Coach_ID", coach_ID) :
                new ObjectParameter("Coach_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_Coach_By_ID_Result>("get_Coach_By_ID", coach_IDParameter);
        }
    
        public virtual ObjectResult<Get_Coach_By_Train_Result> Get_Coach_By_Train(Nullable<int> trainid)
        {
            var trainidParameter = trainid.HasValue ?
                new ObjectParameter("trainid", trainid) :
                new ObjectParameter("trainid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_Coach_By_Train_Result>("Get_Coach_By_Train", trainidParameter);
        }
    
        public virtual ObjectResult<Get_Coach_By_Train_ID_Result> Get_Coach_By_Train_ID(Nullable<int> train_id)
        {
            var train_idParameter = train_id.HasValue ?
                new ObjectParameter("Train_id", train_id) :
                new ObjectParameter("Train_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_Coach_By_Train_ID_Result>("Get_Coach_By_Train_ID", train_idParameter);
        }
    
        public virtual ObjectResult<get_Passenger_By_Email_Result> get_Passenger_By_Email(string email, string phone_Number)
        {
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var phone_NumberParameter = phone_Number != null ?
                new ObjectParameter("Phone_Number", phone_Number) :
                new ObjectParameter("Phone_Number", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_Passenger_By_Email_Result>("get_Passenger_By_Email", emailParameter, phone_NumberParameter);
        }
    
        public virtual ObjectResult<get_Passenger_By_PNR_Result> get_Passenger_By_PNR(string pNR)
        {
            var pNRParameter = pNR != null ?
                new ObjectParameter("PNR", pNR) :
                new ObjectParameter("PNR", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_Passenger_By_PNR_Result>("get_Passenger_By_PNR", pNRParameter);
        }
    
        public virtual ObjectResult<get_Role_By_ID_Result> get_Role_By_ID(Nullable<int> role_ID)
        {
            var role_IDParameter = role_ID.HasValue ?
                new ObjectParameter("Role_ID", role_ID) :
                new ObjectParameter("Role_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_Role_By_ID_Result>("get_Role_By_ID", role_IDParameter);
        }
    
        public virtual ObjectResult<get_Station_By_ID_Result> get_Station_By_ID(Nullable<int> station_ID)
        {
            var station_IDParameter = station_ID.HasValue ?
                new ObjectParameter("Station_ID", station_ID) :
                new ObjectParameter("Station_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_Station_By_ID_Result>("get_Station_By_ID", station_IDParameter);
        }
    
        public virtual ObjectResult<get_Station_By_Status_Result> get_Station_By_Status(string status)
        {
            var statusParameter = status != null ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_Station_By_Status_Result>("get_Station_By_Status", statusParameter);
        }
    
        public virtual ObjectResult<Get_Station_By_Train_ID_Result> Get_Station_By_Train_ID(Nullable<int> train_id)
        {
            var train_idParameter = train_id.HasValue ?
                new ObjectParameter("train_id", train_id) :
                new ObjectParameter("train_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_Station_By_Train_ID_Result>("Get_Station_By_Train_ID", train_idParameter);
        }
    
        public virtual ObjectResult<get_Ticket_By_ID_Result> get_Ticket_By_ID(Nullable<int> ticket_ID)
        {
            var ticket_IDParameter = ticket_ID.HasValue ?
                new ObjectParameter("Ticket_ID", ticket_ID) :
                new ObjectParameter("Ticket_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_Ticket_By_ID_Result>("get_Ticket_By_ID", ticket_IDParameter);
        }
    
        public virtual ObjectResult<Get_Ticket_By_ID_v2_Result> Get_Ticket_By_ID_v2(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_Ticket_By_ID_v2_Result>("Get_Ticket_By_ID_v2", idParameter);
        }
    
        public virtual ObjectResult<get_Ticket_By_PNR_Result> get_Ticket_By_PNR(string pNR)
        {
            var pNRParameter = pNR != null ?
                new ObjectParameter("PNR", pNR) :
                new ObjectParameter("PNR", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_Ticket_By_PNR_Result>("get_Ticket_By_PNR", pNRParameter);
        }
    
        public virtual ObjectResult<get_Ticket_By_TrainID_Result> get_Ticket_By_TrainID(Nullable<int> train_ID, string coach_Type)
        {
            var train_IDParameter = train_ID.HasValue ?
                new ObjectParameter("Train_ID", train_ID) :
                new ObjectParameter("Train_ID", typeof(int));
    
            var coach_TypeParameter = coach_Type != null ?
                new ObjectParameter("Coach_Type", coach_Type) :
                new ObjectParameter("Coach_Type", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_Ticket_By_TrainID_Result>("get_Ticket_By_TrainID", train_IDParameter, coach_TypeParameter);
        }
    
        public virtual ObjectResult<get_Timetable_By_ID_Result> get_Timetable_By_ID(Nullable<int> timetable_ID)
        {
            var timetable_IDParameter = timetable_ID.HasValue ?
                new ObjectParameter("Timetable_ID", timetable_ID) :
                new ObjectParameter("Timetable_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_Timetable_By_ID_Result>("get_Timetable_By_ID", timetable_IDParameter);
        }
    
        public virtual ObjectResult<Get_Timetable_By_Train_ID_Result> Get_Timetable_By_Train_ID(Nullable<int> train_id)
        {
            var train_idParameter = train_id.HasValue ?
                new ObjectParameter("train_id", train_id) :
                new ObjectParameter("train_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_Timetable_By_Train_ID_Result>("Get_Timetable_By_Train_ID", train_idParameter);
        }
    
        public virtual ObjectResult<get_Train_By_ID_Result> get_Train_By_ID(Nullable<int> train_ID)
        {
            var train_IDParameter = train_ID.HasValue ?
                new ObjectParameter("Train_ID", train_ID) :
                new ObjectParameter("Train_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_Train_By_ID_Result>("get_Train_By_ID", train_IDParameter);
        }
    
        public virtual ObjectResult<get_User_By_Username_Result> get_User_By_Username(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_User_By_Username_Result>("get_User_By_Username", usernameParameter);
        }
    
        public virtual ObjectResult<Get_User_By_UserName_v2_Result> Get_User_By_UserName_v2(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_User_By_UserName_v2_Result>("Get_User_By_UserName_v2", usernameParameter);
        }
    
        public virtual ObjectResult<getAll_Coaches_Result> getAll_Coaches()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getAll_Coaches_Result>("getAll_Coaches");
        }
    
        public virtual ObjectResult<getAll_Passengers_Result> getAll_Passengers()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getAll_Passengers_Result>("getAll_Passengers");
        }
    
        public virtual ObjectResult<getAll_Roles_Result> getAll_Roles()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getAll_Roles_Result>("getAll_Roles");
        }
    
        public virtual ObjectResult<getAll_Stations_Result> getAll_Stations()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getAll_Stations_Result>("getAll_Stations");
        }
    
        public virtual ObjectResult<getAll_Tickets_Result> getAll_Tickets()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getAll_Tickets_Result>("getAll_Tickets");
        }
    
        public virtual ObjectResult<getAll_Timetables_Result> getAll_Timetables()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getAll_Timetables_Result>("getAll_Timetables");
        }
    
        public virtual ObjectResult<getAll_Trains_Result> getAll_Trains()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getAll_Trains_Result>("getAll_Trains");
        }
    
        public virtual ObjectResult<getAll_Users_Result> getAll_Users()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getAll_Users_Result>("getAll_Users");
        }
    
        public virtual ObjectResult<login_Result> login(string username, string password)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<login_Result>("login", usernameParameter, passwordParameter);
        }
    
        public virtual ObjectResult<Search_Coach_Type_Result> Search_Coach_Type(Nullable<int> train_ID, string coach_Type)
        {
            var train_IDParameter = train_ID.HasValue ?
                new ObjectParameter("Train_ID", train_ID) :
                new ObjectParameter("Train_ID", typeof(int));
    
            var coach_TypeParameter = coach_Type != null ?
                new ObjectParameter("Coach_Type", coach_Type) :
                new ObjectParameter("Coach_Type", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Search_Coach_Type_Result>("Search_Coach_Type", train_IDParameter, coach_TypeParameter);
        }
    
        public virtual ObjectResult<Search_Station_Result> Search_Station(string station_Name)
        {
            var station_NameParameter = station_Name != null ?
                new ObjectParameter("Station_Name", station_Name) :
                new ObjectParameter("Station_Name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Search_Station_Result>("Search_Station", station_NameParameter);
        }
    
        public virtual ObjectResult<Search_Ticket_By_PNR_Result> Search_Ticket_By_PNR(string pnr)
        {
            var pnrParameter = pnr != null ?
                new ObjectParameter("pnr", pnr) :
                new ObjectParameter("pnr", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Search_Ticket_By_PNR_Result>("Search_Ticket_By_PNR", pnrParameter);
        }
    
        public virtual ObjectResult<Search_Timetable_Result> Search_Timetable(Nullable<int> train_ID)
        {
            var train_IDParameter = train_ID.HasValue ?
                new ObjectParameter("Train_ID", train_ID) :
                new ObjectParameter("Train_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Search_Timetable_Result>("Search_Timetable", train_IDParameter);
        }
    
        public virtual ObjectResult<Search_Train_Result> Search_Train(Nullable<int> origin_Station_ID, Nullable<int> destination_Station_ID)
        {
            var origin_Station_IDParameter = origin_Station_ID.HasValue ?
                new ObjectParameter("Origin_Station_ID", origin_Station_ID) :
                new ObjectParameter("Origin_Station_ID", typeof(int));
    
            var destination_Station_IDParameter = destination_Station_ID.HasValue ?
                new ObjectParameter("Destination_Station_ID", destination_Station_ID) :
                new ObjectParameter("Destination_Station_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Search_Train_Result>("Search_Train", origin_Station_IDParameter, destination_Station_IDParameter);
        }
    
        public virtual ObjectResult<Search_Train_By_Train_id_Result> Search_Train_By_Train_id(Nullable<int> train_id)
        {
            var train_idParameter = train_id.HasValue ?
                new ObjectParameter("train_id", train_id) :
                new ObjectParameter("train_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Search_Train_By_Train_id_Result>("Search_Train_By_Train_id", train_idParameter);
        }
    
        public virtual ObjectResult<Search_Train_Information_Result> Search_Train_Information(Nullable<int> origin_Station_ID, Nullable<int> destination_Station_ID, Nullable<System.DateTime> departure_Date)
        {
            var origin_Station_IDParameter = origin_Station_ID.HasValue ?
                new ObjectParameter("Origin_Station_ID", origin_Station_ID) :
                new ObjectParameter("Origin_Station_ID", typeof(int));
    
            var destination_Station_IDParameter = destination_Station_ID.HasValue ?
                new ObjectParameter("Destination_Station_ID", destination_Station_ID) :
                new ObjectParameter("Destination_Station_ID", typeof(int));
    
            var departure_DateParameter = departure_Date.HasValue ?
                new ObjectParameter("Departure_Date", departure_Date) :
                new ObjectParameter("Departure_Date", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Search_Train_Information_Result>("Search_Train_Information", origin_Station_IDParameter, destination_Station_IDParameter, departure_DateParameter);
        }
    
        public virtual ObjectResult<Search_Train_TimeTable_Result> Search_Train_TimeTable(Nullable<int> origin_Station_ID, Nullable<int> destination_Station_ID, Nullable<System.DateTime> departure_Date)
        {
            var origin_Station_IDParameter = origin_Station_ID.HasValue ?
                new ObjectParameter("Origin_Station_ID", origin_Station_ID) :
                new ObjectParameter("Origin_Station_ID", typeof(int));
    
            var destination_Station_IDParameter = destination_Station_ID.HasValue ?
                new ObjectParameter("Destination_Station_ID", destination_Station_ID) :
                new ObjectParameter("Destination_Station_ID", typeof(int));
    
            var departure_DateParameter = departure_Date.HasValue ?
                new ObjectParameter("Departure_Date", departure_Date) :
                new ObjectParameter("Departure_Date", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Search_Train_TimeTable_Result>("Search_Train_TimeTable", origin_Station_IDParameter, destination_Station_IDParameter, departure_DateParameter);
        }
    
        public virtual ObjectResult<Search_Username_By_ID_Result> Search_Username_By_ID(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Search_Username_By_ID_Result>("Search_Username_By_ID", usernameParameter);
        }
    
        public virtual int Update_Coaches(Nullable<int> coach_ID, string coach_Type, Nullable<int> train_ID, Nullable<int> number_Of_Seats, Nullable<double> price, string status)
        {
            var coach_IDParameter = coach_ID.HasValue ?
                new ObjectParameter("Coach_ID", coach_ID) :
                new ObjectParameter("Coach_ID", typeof(int));
    
            var coach_TypeParameter = coach_Type != null ?
                new ObjectParameter("Coach_Type", coach_Type) :
                new ObjectParameter("Coach_Type", typeof(string));
    
            var train_IDParameter = train_ID.HasValue ?
                new ObjectParameter("Train_ID", train_ID) :
                new ObjectParameter("Train_ID", typeof(int));
    
            var number_Of_SeatsParameter = number_Of_Seats.HasValue ?
                new ObjectParameter("Number_Of_Seats", number_Of_Seats) :
                new ObjectParameter("Number_Of_Seats", typeof(int));
    
            var priceParameter = price.HasValue ?
                new ObjectParameter("Price", price) :
                new ObjectParameter("Price", typeof(double));
    
            var statusParameter = status != null ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Update_Coaches", coach_IDParameter, coach_TypeParameter, train_IDParameter, number_Of_SeatsParameter, priceParameter, statusParameter);
        }
    
        public virtual int Update_Info(string username, string email, string phone, string gender)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var phoneParameter = phone != null ?
                new ObjectParameter("phone", phone) :
                new ObjectParameter("phone", typeof(string));
    
            var genderParameter = gender != null ?
                new ObjectParameter("gender", gender) :
                new ObjectParameter("gender", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Update_Info", usernameParameter, emailParameter, phoneParameter, genderParameter);
        }
    
        public virtual int Update_Passengers(string pNR, string passenger_Name, Nullable<System.DateTime> date_Of_Birth, string card_Code, string gender, string email, string phone_Number, string address)
        {
            var pNRParameter = pNR != null ?
                new ObjectParameter("PNR", pNR) :
                new ObjectParameter("PNR", typeof(string));
    
            var passenger_NameParameter = passenger_Name != null ?
                new ObjectParameter("Passenger_Name", passenger_Name) :
                new ObjectParameter("Passenger_Name", typeof(string));
    
            var date_Of_BirthParameter = date_Of_Birth.HasValue ?
                new ObjectParameter("Date_Of_Birth", date_Of_Birth) :
                new ObjectParameter("Date_Of_Birth", typeof(System.DateTime));
    
            var card_CodeParameter = card_Code != null ?
                new ObjectParameter("Card_Code", card_Code) :
                new ObjectParameter("Card_Code", typeof(string));
    
            var genderParameter = gender != null ?
                new ObjectParameter("Gender", gender) :
                new ObjectParameter("Gender", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var phone_NumberParameter = phone_Number != null ?
                new ObjectParameter("Phone_Number", phone_Number) :
                new ObjectParameter("Phone_Number", typeof(string));
    
            var addressParameter = address != null ?
                new ObjectParameter("Address", address) :
                new ObjectParameter("Address", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Update_Passengers", pNRParameter, passenger_NameParameter, date_Of_BirthParameter, card_CodeParameter, genderParameter, emailParameter, phone_NumberParameter, addressParameter);
        }
    
        public virtual int Update_Password(string username, string password)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Update_Password", usernameParameter, passwordParameter);
        }
    
        public virtual int Update_Roles(Nullable<int> role_ID, string role_Name)
        {
            var role_IDParameter = role_ID.HasValue ?
                new ObjectParameter("Role_ID", role_ID) :
                new ObjectParameter("Role_ID", typeof(int));
    
            var role_NameParameter = role_Name != null ?
                new ObjectParameter("Role_Name", role_Name) :
                new ObjectParameter("Role_Name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Update_Roles", role_IDParameter, role_NameParameter);
        }
    
        public virtual int Update_Stations(Nullable<int> station_ID, string station_Name, Nullable<double> latitude, Nullable<double> longtitude, string status)
        {
            var station_IDParameter = station_ID.HasValue ?
                new ObjectParameter("Station_ID", station_ID) :
                new ObjectParameter("Station_ID", typeof(int));
    
            var station_NameParameter = station_Name != null ?
                new ObjectParameter("Station_Name", station_Name) :
                new ObjectParameter("Station_Name", typeof(string));
    
            var latitudeParameter = latitude.HasValue ?
                new ObjectParameter("Latitude", latitude) :
                new ObjectParameter("Latitude", typeof(double));
    
            var longtitudeParameter = longtitude.HasValue ?
                new ObjectParameter("Longtitude", longtitude) :
                new ObjectParameter("Longtitude", typeof(double));
    
            var statusParameter = status != null ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Update_Stations", station_IDParameter, station_NameParameter, latitudeParameter, longtitudeParameter, statusParameter);
        }
    
        public virtual int Update_Tickets(Nullable<int> ticket_ID, string pNR, string passenger_Type, string status, Nullable<int> train_ID, Nullable<System.DateTime> departure_Date, Nullable<System.TimeSpan> departure_Time, string coach_Type, Nullable<double> price)
        {
            var ticket_IDParameter = ticket_ID.HasValue ?
                new ObjectParameter("Ticket_ID", ticket_ID) :
                new ObjectParameter("Ticket_ID", typeof(int));
    
            var pNRParameter = pNR != null ?
                new ObjectParameter("PNR", pNR) :
                new ObjectParameter("PNR", typeof(string));
    
            var passenger_TypeParameter = passenger_Type != null ?
                new ObjectParameter("Passenger_Type", passenger_Type) :
                new ObjectParameter("Passenger_Type", typeof(string));
    
            var statusParameter = status != null ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(string));
    
            var train_IDParameter = train_ID.HasValue ?
                new ObjectParameter("Train_ID", train_ID) :
                new ObjectParameter("Train_ID", typeof(int));
    
            var departure_DateParameter = departure_Date.HasValue ?
                new ObjectParameter("Departure_Date", departure_Date) :
                new ObjectParameter("Departure_Date", typeof(System.DateTime));
    
            var departure_TimeParameter = departure_Time.HasValue ?
                new ObjectParameter("Departure_Time", departure_Time) :
                new ObjectParameter("Departure_Time", typeof(System.TimeSpan));
    
            var coach_TypeParameter = coach_Type != null ?
                new ObjectParameter("Coach_Type", coach_Type) :
                new ObjectParameter("Coach_Type", typeof(string));
    
            var priceParameter = price.HasValue ?
                new ObjectParameter("Price", price) :
                new ObjectParameter("Price", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Update_Tickets", ticket_IDParameter, pNRParameter, passenger_TypeParameter, statusParameter, train_IDParameter, departure_DateParameter, departure_TimeParameter, coach_TypeParameter, priceParameter);
        }
    
        public virtual int Update_Timetables(Nullable<int> timetable_ID, Nullable<System.DateTime> departure_Date, Nullable<System.TimeSpan> departure_Time, Nullable<System.DateTime> arrival_Date, Nullable<System.TimeSpan> arrival_Time, Nullable<double> distance, Nullable<int> train_ID)
        {
            var timetable_IDParameter = timetable_ID.HasValue ?
                new ObjectParameter("Timetable_ID", timetable_ID) :
                new ObjectParameter("Timetable_ID", typeof(int));
    
            var departure_DateParameter = departure_Date.HasValue ?
                new ObjectParameter("Departure_Date", departure_Date) :
                new ObjectParameter("Departure_Date", typeof(System.DateTime));
    
            var departure_TimeParameter = departure_Time.HasValue ?
                new ObjectParameter("Departure_Time", departure_Time) :
                new ObjectParameter("Departure_Time", typeof(System.TimeSpan));
    
            var arrival_DateParameter = arrival_Date.HasValue ?
                new ObjectParameter("Arrival_Date", arrival_Date) :
                new ObjectParameter("Arrival_Date", typeof(System.DateTime));
    
            var arrival_TimeParameter = arrival_Time.HasValue ?
                new ObjectParameter("Arrival_Time", arrival_Time) :
                new ObjectParameter("Arrival_Time", typeof(System.TimeSpan));
    
            var distanceParameter = distance.HasValue ?
                new ObjectParameter("Distance", distance) :
                new ObjectParameter("Distance", typeof(double));
    
            var train_IDParameter = train_ID.HasValue ?
                new ObjectParameter("Train_ID", train_ID) :
                new ObjectParameter("Train_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Update_Timetables", timetable_IDParameter, departure_DateParameter, departure_TimeParameter, arrival_DateParameter, arrival_TimeParameter, distanceParameter, train_IDParameter);
        }
    
        public virtual int Update_Trains(Nullable<int> train_ID, string train_Name, Nullable<int> origin_Station_ID, Nullable<int> destination_Station_ID, string status, string train_Type)
        {
            var train_IDParameter = train_ID.HasValue ?
                new ObjectParameter("Train_ID", train_ID) :
                new ObjectParameter("Train_ID", typeof(int));
    
            var train_NameParameter = train_Name != null ?
                new ObjectParameter("Train_Name", train_Name) :
                new ObjectParameter("Train_Name", typeof(string));
    
            var origin_Station_IDParameter = origin_Station_ID.HasValue ?
                new ObjectParameter("Origin_Station_ID", origin_Station_ID) :
                new ObjectParameter("Origin_Station_ID", typeof(int));
    
            var destination_Station_IDParameter = destination_Station_ID.HasValue ?
                new ObjectParameter("Destination_Station_ID", destination_Station_ID) :
                new ObjectParameter("Destination_Station_ID", typeof(int));
    
            var statusParameter = status != null ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(string));
    
            var train_TypeParameter = train_Type != null ?
                new ObjectParameter("Train_Type", train_Type) :
                new ObjectParameter("Train_Type", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Update_Trains", train_IDParameter, train_NameParameter, origin_Station_IDParameter, destination_Station_IDParameter, statusParameter, train_TypeParameter);
        }
    
        public virtual int Update_Users(string username, string password, string email, string phone_Number, string gender, string security_Code, Nullable<int> role_ID)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var phone_NumberParameter = phone_Number != null ?
                new ObjectParameter("Phone_Number", phone_Number) :
                new ObjectParameter("Phone_Number", typeof(string));
    
            var genderParameter = gender != null ?
                new ObjectParameter("Gender", gender) :
                new ObjectParameter("Gender", typeof(string));
    
            var security_CodeParameter = security_Code != null ?
                new ObjectParameter("Security_Code", security_Code) :
                new ObjectParameter("Security_Code", typeof(string));
    
            var role_IDParameter = role_ID.HasValue ?
                new ObjectParameter("Role_ID", role_ID) :
                new ObjectParameter("Role_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Update_Users", usernameParameter, passwordParameter, emailParameter, phone_NumberParameter, genderParameter, security_CodeParameter, role_IDParameter);
        }
    
        public virtual int Add_Tickets(string pNR, string passenger_Type, string status, Nullable<int> train_ID, Nullable<System.DateTime> departure_Date, Nullable<System.TimeSpan> departure_Time, string coach_type, Nullable<double> price)
        {
            var pNRParameter = pNR != null ?
                new ObjectParameter("PNR", pNR) :
                new ObjectParameter("PNR", typeof(string));
    
            var passenger_TypeParameter = passenger_Type != null ?
                new ObjectParameter("Passenger_Type", passenger_Type) :
                new ObjectParameter("Passenger_Type", typeof(string));
    
            var statusParameter = status != null ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(string));
    
            var train_IDParameter = train_ID.HasValue ?
                new ObjectParameter("Train_ID", train_ID) :
                new ObjectParameter("Train_ID", typeof(int));
    
            var departure_DateParameter = departure_Date.HasValue ?
                new ObjectParameter("Departure_Date", departure_Date) :
                new ObjectParameter("Departure_Date", typeof(System.DateTime));
    
            var departure_TimeParameter = departure_Time.HasValue ?
                new ObjectParameter("Departure_Time", departure_Time) :
                new ObjectParameter("Departure_Time", typeof(System.TimeSpan));
    
            var coach_typeParameter = coach_type != null ?
                new ObjectParameter("Coach_type", coach_type) :
                new ObjectParameter("Coach_type", typeof(string));
    
            var priceParameter = price.HasValue ?
                new ObjectParameter("Price", price) :
                new ObjectParameter("Price", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Add_Tickets", pNRParameter, passenger_TypeParameter, statusParameter, train_IDParameter, departure_DateParameter, departure_TimeParameter, coach_typeParameter, priceParameter);
        }
    
        public virtual ObjectResult<Get_Train_Des_Result> Get_Train_Des(Nullable<int> origin_Station_ID, Nullable<System.DateTime> departure_Date)
        {
            var origin_Station_IDParameter = origin_Station_ID.HasValue ?
                new ObjectParameter("Origin_Station_ID", origin_Station_ID) :
                new ObjectParameter("Origin_Station_ID", typeof(int));
    
            var departure_DateParameter = departure_Date.HasValue ?
                new ObjectParameter("Departure_Date", departure_Date) :
                new ObjectParameter("Departure_Date", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_Train_Des_Result>("Get_Train_Des", origin_Station_IDParameter, departure_DateParameter);
        }
    
        public virtual ObjectResult<Get_Train_Des2_Result> Get_Train_Des2(Nullable<int> origin_Station_ID, Nullable<System.DateTime> departure_Date)
        {
            var origin_Station_IDParameter = origin_Station_ID.HasValue ?
                new ObjectParameter("Origin_Station_ID", origin_Station_ID) :
                new ObjectParameter("Origin_Station_ID", typeof(int));
    
            var departure_DateParameter = departure_Date.HasValue ?
                new ObjectParameter("Departure_Date", departure_Date) :
                new ObjectParameter("Departure_Date", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_Train_Des2_Result>("Get_Train_Des2", origin_Station_IDParameter, departure_DateParameter);
        }
    
        public virtual ObjectResult<Get_Train_Des_Schedule_Result> Get_Train_Des_Schedule(Nullable<int> origin_Station_ID, Nullable<System.DateTime> departure_Date)
        {
            var origin_Station_IDParameter = origin_Station_ID.HasValue ?
                new ObjectParameter("Origin_Station_ID", origin_Station_ID) :
                new ObjectParameter("Origin_Station_ID", typeof(int));
    
            var departure_DateParameter = departure_Date.HasValue ?
                new ObjectParameter("Departure_Date", departure_Date) :
                new ObjectParameter("Departure_Date", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_Train_Des_Schedule_Result>("Get_Train_Des_Schedule", origin_Station_IDParameter, departure_DateParameter);
        }
    
        public virtual ObjectResult<Get_train_By_OS_Result> Get_train_By_OS(Nullable<int> origin_Station_ID)
        {
            var origin_Station_IDParameter = origin_Station_ID.HasValue ?
                new ObjectParameter("Origin_Station_ID", origin_Station_ID) :
                new ObjectParameter("Origin_Station_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_train_By_OS_Result>("Get_train_By_OS", origin_Station_IDParameter);
        }
    
        public virtual ObjectResult<Get_Train_By_Time_Sche_Result> Get_Train_By_Time_Sche(Nullable<int> train_id, Nullable<System.DateTime> departure_Date)
        {
            var train_idParameter = train_id.HasValue ?
                new ObjectParameter("Train_id", train_id) :
                new ObjectParameter("Train_id", typeof(int));
    
            var departure_DateParameter = departure_Date.HasValue ?
                new ObjectParameter("Departure_Date", departure_Date) :
                new ObjectParameter("Departure_Date", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_Train_By_Time_Sche_Result>("Get_Train_By_Time_Sche", train_idParameter, departure_DateParameter);
        }
    
        public virtual ObjectResult<Get_Train_By_Time_Sche2_Result> Get_Train_By_Time_Sche2(Nullable<int> train_id, Nullable<System.DateTime> departure_Date)
        {
            var train_idParameter = train_id.HasValue ?
                new ObjectParameter("Train_id", train_id) :
                new ObjectParameter("Train_id", typeof(int));
    
            var departure_DateParameter = departure_Date.HasValue ?
                new ObjectParameter("Departure_Date", departure_Date) :
                new ObjectParameter("Departure_Date", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_Train_By_Time_Sche2_Result>("Get_Train_By_Time_Sche2", train_idParameter, departure_DateParameter);
        }
    }
}
